stages:
  - tests

tests:
  stage: tests
  image: docker
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  tags:
    - ng-docker-dind
  script:
    - docker build -t qgis_headless:focal -f Dockerfile.focal .
    - docker run --rm qgis_headless:focal ./pytest-runner
  when: manual

