stages:
  - lint
  - test

pre_commit_check:
  stage: lint
  tags: [nextgis-docker]
  image: python:3.11
  before_script:
    - pip install pre-commit
  script:
    - pre-commit run --all-files
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

.run_tests_job:
  stage: test
  tags: [nextgis-docker]
  image: docker
  variables:
    REPORT_DIR: report/${DISTRO}
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - docker build -t qgis_headless:${DISTRO} -f Dockerfile.${DISTRO} .
    - mkdir -p ${REPORT_DIR}
    - docker run -v ${CI_PROJECT_DIR}/${REPORT_DIR}:/mnt --rm qgis_headless:${DISTRO} ./pytest-runner
  allow_failure: false
  artifacts:
    when: always
    paths:
      - ${REPORT_DIR}/rspec.xml
    reports:
      junit: ${REPORT_DIR}/rspec.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

test_focal:
  extends: .run_tests_job
  variables:
    DISTRO: focal

test_jammy:
  extends: .run_tests_job
  variables:
    DISTRO: jammy

test_jammy_latest:
  extends: .run_tests_job
  variables:
    DISTRO: jammy-latest
