.job_cmn:
  image: docker
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  tags:
    - ng-docker-dind
  script:
    - docker build -t qgis_headless -f Dockerfile.$CI_JOB_STAGE .
    - mkdir report
    - docker run -v ${CI_PROJECT_DIR}/report:/mnt --rm qgis_headless ./pytest-runner
  allow_failure: true
  artifacts:
    when: always
    paths:
      - ${CI_PROJECT_DIR}/report/rspec.xml
    reports:
      junit: ${CI_PROJECT_DIR}/report/rspec.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"


stages:
  - focal
  - jammy
  - jammy-latest

test_focal_job:
  extends: .job_cmn
  stage: focal

test_jammy_job:
  extends: .job_cmn
  stage: jammy

test_jammy_latest_job:
  extends: .job_cmn
  stage: jammy-latest
