.job_cmn:
  image: docker
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  tags:
    - ng-docker-dind
  script:
    - docker build -t qgis_headless -f Dockerfile.$CI_JOB_STAGE .
    - docker run --rm qgis_headless ./pytest-runner
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"


stages:
  - focal
  - jammy

test_focal_job:
  extends: .job_cmn
  stage: focal

test_jammy_job:
  extends: .job_cmn
  stage: jammy
